language: c

dist: xenial

before_script:
  - git clone https://github.com/syndbg/goenv.git ${HOME}/.goenv
  - PATH=${HOME}/.goenv/bin:${PATH}
  - eval "$(goenv init -)"
  - goenv install 1.12.5
  - goenv global 1.12.5
  - mkdir -p ~/.goenv/plugins/
  - ln -nfs "$PWD" ~/.goenv/plugins/goenv-install-dep
  - goenv rehash

script:
  - goenv install-dep
  - '[ "$(which dep)" == "${HOME}/.goenv/shims/dep" ]'
  - '[ "$(goenv which dep)" == "$(goenv prefix)/bin/dep" ]'
  - dep version
  - ls -l "$(goenv prefix)/bin/dep"
